name: Java Simple App
on:
  push:
    branches:
      - master
jobs:
  build-test-deploy:
    uses: ${{ vars.WORKFLOW_PATH }}
    permissions:
      checks: write
      pull-requests: write
    secrets:
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    with:
      JAVA_VERSION: ${{ vars.JAVA_VERSION }}
      ARTIFACTORY_USERNAME:  ${{ vars.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_SETTINGS_XML_URL: ${{ vars.ARTIFACTORY_SETTINGS_XML_URL }}
      MAVEN_POM_FILE: ${{ vars.MAVEN_POM_FILE }}
      MAVEN_GOALS: ${{ vars.MAVEN_GOALS }}
      MAVEN_OPTS: ${{ vars.MAVEN_OPTS }}
